#
# Information on what these settings mean can be found on the wiki located at
# http://github.com/OreCruncher/WorkRewards/wiki
#
sendPlayerRewardMessageThreshold: 0.0
rewards:
  MOB_SPAWNER: 0.0
  QUARTZ_ORE: 0.0
  REDSTONE_ORE: 0.0
  GLOWING_REDSTONE_ORE: 0.0
  DIAMOND_ORE: 0.0
  LAPIS_ORE: 0.0
  GLOWSTONE: 0.0
  MONSTER_EGGS: 0.0
  EMERALD_ORE: 0.0
  COAL_ORE: 0.0
